import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { options } from "@/lib/hotToast";
import ThemeProvider from "@/context/ThemeProvider";
import ClientThemeWrapper from "@/context/ClientThemeWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Product Mix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      data-theme="dark"
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <ClientThemeWrapper>
            {children}
          </ClientThemeWrapper>
        </ThemeProvider>
        <Toaster 
          position="top-center" 
          toastOptions={options} 
          gutter={24} />
      </body>
    </html>
  );
}
