import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { options } from "@/lib/hotToast";
import ThemeProvider from "@/context/ThemeProvider";
import ClientThemeWrapper from "@/context/ClientThemeWrapper";
import SessionProvider, { defaultSession } from "@/context/SessionContext";
import { auth } from "../../auth";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Product Mix",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth() || defaultSession

  return (
    <html lang="en" suppressHydrationWarning>
      <body
      // data-theme="dark"
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}> 
        <ThemeProvider>
          <ClientThemeWrapper>
      
            {children}
          <Toaster 
            position="top-center" 
            toastOptions={options} 
            gutter={24} />
          </ClientThemeWrapper>
        </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
